name: release

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: write

jobs:
  auto_bump_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          go run ./internal/ci/auto-bump-go-by-creating-tag
