name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release_kiln:
    name: "Release Kiln"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.RELEEN_GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true

      - name: Build
        run: go build ./...
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.RELENG_CI_BOT_KEY }}

      - name: Unit Test
        env:
          RELEEN_GITHUB_TOKEN: ${{ secrets.RELEEN_GITHUB_TOKEN }}
        run: |
          export GITHUB_TOKEN="${RELEEN_GITHUB_TOKEN}"
          go test ./...

      - name: Acceptance Tests
        env:
          CGO_ENABLED: '0'
          RELEEN_GITHUB_TOKEN: ${{ secrets.RELEEN_GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          export GITHUB_TOKEN="${RELEEN_GITHUB_TOKEN}"

          set -x
          go test --run '(using_kiln|baking_a_tile|generating_release_notes|updating_)' \
            -v --timeout 24h --tags acceptance \
            github.com/pivotal-cf/kiln/internal/acceptance/workflows
          
          git reset --hard HEAD

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
